# DO : i permet, à partir d'un array de prix, de connaître le meilleur jour 
# d'achat et le meilleur jour de revente pour faire le maximum de bénéfices
# NB : N'oublie pas qu’on ne peut pas vendre avant d'avoir acheté…